#!/usr/bin/env bash

[[ -n "$(sft list-accounts --output json | jq '.[] | select(.account == "kajabi") | .id')" ]] || {
  echo 'sft not enrolled. You probably need to run `sft enroll --team kajabi`' >&2
  exit 1
}
